### PR TITLE
Updating Italian translations and adding some new ones

### PR DESCRIPTION
**Pull request by DepaMarco**
Update and/or complete Italian translations for plugins:
* 'access.ajxp_conf''
* 'access.ajxp_home'
* 'access.ajxp_shared'
* 'access.ajxp_user'
* 'action.cart'

Added Italian translation for plugins:
* 'action.compression'
* 'action.antivirus'

### CODE REVIEW

**Comment by cdujeu** [comment]
Hello,
Just leaving for a 2 weeks holiday, so don't be surprised if I don't merge right now :-)
Charles

**Comment by DepaMarco** [comment]
Ahahah I see that you know how I'm done :P thanks for the info.
Good Holidays!!!

**Comment by DepaMarco** [comment]
You can merge :D thanks

**Comment by cdujeu** [comment]
Done ;-)

**Pull request merged**
