### PR TITLE
Option to zip downloading files on the fly

### PR DESCRIPTION
**Pull request by blackwarthog**
So pydio can directly write the zip file to an output stream which is
connected to the user's browser without creating any temporary files.

### CODE REVIEW

**Comment by morevnaproject** [comment]
@cdujeu Ping. The CLA is signed now. ^__^

**Comment by cdujeu** [comment]
@blackwarthog @morevnaproject sorry this one has been broken by the huge refactoring performed in another branch, that is now back to develop. 
Could you kindly publish a new PR ? You probably have to restart from scratch (inc. the changes in PclZip), and use an AsyncResponseStream() object to trigger the zip operation in a callback. Feel free to ask questions if needed.

**Comment by blackwarthog** [comment]
Seems bug [here](https://github.com/pydio/pydio-core/blob/develop/core/src/core/src/pydio/Core/Http/Response/FileReaderResponse.php#L220), i'm not sure:
 $isFile = ($data !== null) && !$confGzip;

I think should be: $data === null

**Comment by cdujeu** [comment]
mmm you're probably right, i'll recheck

**Comment by cdujeu** [comment]
@blackwarthog fixed in 094845d6567abf0a2d7303d767c3f8f209533de4, thx!
Are you working on re-adapting this dev ? If so, please submit ASAP as we are in codefreeze right now :-)

**Comment by morevnaproject** [comment]
Hello @cdujeu! Here is re-adaptation - #1247. ^__^

**Pull request merged**
