### PR TITLE
Add and remove roles based on LDAP group membership

### PR DESCRIPTION
**Pull request by terminal-addict**
Honour the GFilter in the Authentication settings so that only filtered LDAP groups are mapped to roles. User roles are added and removed according to user membership in LDAP groups.

### CODE REVIEW

**Comment by cdujeu** [comment]
@c12simple what's the status here? did you finally integrate these changes ?

**Comment by c12simple** [comment]
Hi All,
Is this the case?
https://pyd.io/f/topic/ad-groups-pydio-roles-outdated-group-memberships-are-not-removed-from-roles/

**Comment by terminal-addict** [comment]
This does seem to mostly address the issue. Note that gfilter is
ignored, so ALL ldap groups the user is memberof are mapped to roles in
Pydio. This leads to a LOT of unused roles (in our case). We only care
about groups that match our filter. 

Time is very short lately, but I
can try to figure out if gfilter can be used this way. Is there another
intent for gfilter? Does it work as intended in another scenario? 

Kyle


On Sat, 24 Jan 2015 03:56:10 -0800, c12simple  wrote:  

Hi All,
 Is
this the
case?
https://pyd.io/f/topic/ad-groups-pydio-roles-outdated-group-memberships-are-not-removed-from-roles/
[1] 

--
Reply to this email directly or view it on GitHub [2]. 




Links:
------
[1]
https://pyd.io/f/topic/ad-groups-pydio-roles-outdated-group-memberships-are-not-removed-from-roles/
[2]
https://github.com/pydio/pydio-core/pull/660#issuecomment-71313498

**Comment by cdujeu** [comment]
probably out-of-date, reopen if needed

**Pull request closed without merging**
