### PR TITLE
Templatepath variables added

### PR DESCRIPTION
**Pull request by mawit**
Hi

I added the possibility to use the parameter AJXP_WORKSPACE_UUID in a workspace template. This then will be replaced by the uuid of the workspace. I also added the variable AJXP_WORKSPACE_UUID to be replaced with the slug of the workspace.
This was already discussed in #978.

### CODE REVIEW

**Comment by cdujeu** [comment]
@mawit 
Don't want to relaunch yet another discussion but.. :-) Why adding this only for a workspace template? Why not adding this possibility for all workspaces ? Can you just re-explain the usecase? 
Otherwise seems ok to me.
Thx!

**Comment by cdujeu** [comment]
@mawit any thoughts? Please answer quickly :-)

**Comment by mawit** [comment]
@cdujeu Thank's for your response.
I think it's a good idea to add it also to all workspaces.
My problem is, that I have no idea how to add this to "normal" workspaces.

**Comment by mawit** [comment]
We have the usecase that we want to delegate the creation of workspaces but it must not be possible to add two workspaces which points to the same directory, which is possible without this.

**Comment by cdujeu** [comment]
Merging as is for the moment.

**Pull request merged**
