### PR TITLE
Menu "Download" with PowerFS failed if accent in folder under the files selected

### PR DESCRIPTION
**Pull request by Ellega**
Menu "Download" with PowerFS failed if accent in folder under the files selected
Because in this case archive_name has accent

### CODE REVIEW

**Comment by cdujeu** [comment]
then you should do the same at line 166, right?
Can you replace the "/" with DIRECTORY_SEPARATOR as well? (in both places)

**Comment by Ellega** [comment]
ok
And with your code in "class.AJXP_Controller.php" (#835) ?

**Comment by cdujeu** [comment]
mmm, i don't know, from what I understand from you it did actually not make any changes for you, right?
Let's not put it in the same PR anyway.
-c

**Comment by Ellega** [comment]
Not for me but for you :-) No ? You haven't got any pb with IIS :  "I had the same problem on IIS, but the Archive file was not created at all". (see #835)

Ok I make a new PR for "class.AJXP_Controller.php"

**Comment by Ellega** [comment]
PR Updated !

**Comment by cdujeu** [comment]
forget the other PR, i will retest everything is check if it was not a side-effect.

**Comment by Ellega** [comment]
Ok

**Pull request closed without merging**
