### PR TITLE
updated umlauts and some bad translations/grammar

### PR DESCRIPTION
**Pull request by kluckow**

### CODE REVIEW

**Comment by huzergackl** [comment]
Hi and thanks for contributing!

You did good work. Don't know if you plan to do further changes beside updating the german umlauts.

If so just keep in mind to replace words that are half german and half english with a german synonym.
e.g. "Upload" => "Hochladen"
or "Upload-Limit" => "Limit"

Also have a look at how the same word is translated in other parts of the application to keep them equal. (e.g. "Optionen" => "Einstellungen")

Dont forget to do a quick review in user interface to ensure that everything is correct (length in ui, etc.)

I just did a view minor changes while reviewing (most changes are not in your code):
https://github.com/pydio/pydio-core/pull/890

Stefan

**Comment by kluckow** [comment]
Thank you huzergackl,

I might do further german translation.

You mentioned "Upload" and "Upload-Limit". There are english words like
these for example, that you do not need to translate that strict into
german.
"Upload" is one of many other words you do not need to translate.
Nowadays there is a lot of english in the german language. It is almost
weird to see "Hochladen".
And so the "Upload-Limit" is also perfect as translation. This is just a
suggestion, but I am not the only german who thinks that way. But of
course, the aspect of keeping terms equal all over Pydio is very important.

So next time I will be more careful and check other i18n's to do so.

kluckow
Am 31.03.2015 21:26 schrieb "huzergackl" <notifications@github.com>:
>
> Hi and thanks for contributing!
>
> You did good work. Don't know if you plan to do further changes beside
updating the german umlauts.
>
> If so just keep in mind to replace words that are half german and half
english with a german synonym.
> e.g. "Upload" => "Hochladen"
> or "Upload-Limit" => "Limit"
>
> Also have a look at how the same word is translated in other parts of the
application to keep them equal. (e.g. "Optionen" => "Einstellungen")
>
> Dont forget to do a quick review in user interface to ensure that
everything is correct (length in ui, etc.)
>
> I just did a view minor changes while reviewing (most changes are not in
your code):

**Comment by huzergackl** [comment]
Upload is one of the words, i am not sure either and i dont want to bring in my personal preference.

The word upload is already in Duden where you can see how common it is. But this level is the same for "Hochladen" or "Upload". Arguments for "Hochladen" instead of upload is, that "Hochladen" is already used many times (e.g. for upload button) and that other Services like Dropbox also use "Hochladen".

**Comment by kluckow** [comment]
Ah ok. Like I said, its probably more important to keep terms equal and on
a level that users are used to.

But I would not rely too much on the Duden.
There is a word called "Denglisch" in the german Duden.
It combines the words "Deutsch" and "Englisch" into one. And it just came
up, because there is such a change going on in the german language.
That is what I meant.
So sometimes it is way more attractive for an user to see the english term
than the german one.

kluckow

2015-04-01 16:23 GMT+02:00 huzergackl <notifications@github.com>:

**Comment by cdujeu** [comment]
Hi guys, seeing this discussion, I'll wait for your GO before merging #890 , just tell me :-)

**Pull request merged**
