### PR TITLE
Added SMB lib based SMB access plugin

### PR DESCRIPTION
**Pull request by mwehr**
Hi,

This is an access.smb plugin based on the excellent [icewind1991/SMB] (https://github.com/icewind1991/SMB) library.
I've done one modification in the NativeFileInfo.php -> made stats() public!

Feel free to add it to pydio, maybe as the new major access.smb. :-)
So far I have it running for 2 months without problems.

regards,

Mario

### CODE REVIEW

**Comment by cdujeu** [comment]
Hey Mario, this is great, and promising! 
One question, could you push ONLY the pydio-specific code, without the third-party library? Or do you make modifications in the library?
-c

**Comment by mwehr** [comment]
Hi,

Yes I did one modification in NativeFileInfo.php

**Comment by c12simple** [comment]
hello @mwehr,
Did you test this plugins with smbclient command

**Comment by mwehr** [comment]
I have to admit,... only partial, I primarly focused on the lib-smb implementation.
Do you have problems with the smblient part?

**Comment by c12simple** [comment]
Hello,
Yes, I have tested and it works well with lib-smb. Howerver, the part of smbclient does not work

**Comment by mwehr** [comment]
Hi,
In the next few weeks I'll have time to investigate the smbclient part.

**Pull request closed without merging**
