### PR TITLE
Blind update with my production version of elasticsearch plugin

### PR DESCRIPTION
**Pull request by ciropom**
Blind update with my production version of elasticsearch plugin:
It should be merged with know-how about what was changed from my last update (pydio 6.0)

### CODE REVIEW

**Comment by cdujeu** [comment]
I'm working on this, will grab your changes and integrate them manually, this plugin needs a deeper reworking. Thx for posting.

**Comment by cdujeu** [comment]
FYI, massive refactoring in the last commits.
Interested to here about your tests. You may have to relaunch indexation to make sure everything is working properly.
-c

**Comment by ciropom** [comment]
OK I will test the changes as soon as they will be relased. 
I will keep my production version updated. Are you planning to relase these changes soon?

**Comment by cdujeu** [comment]
if you are running 6.0.6 your version must be quite out-of-date, no?

**Comment by ciropom** [comment]
Yes I'm running 6.0.6 but the file has not changed.. it is not the same as in your repo

**Pull request closed without merging**
