### PR TITLE
File ".ajxp_meta" must be Hidden if Windows OS

### LINKED ISSUE #532: if exist ".ajxp_meta" it must be excluded when "Download All" in Minisite
Actually ".ajxp_meta" is in the archive ZIP  when action "Download All" in Minisite.

### PR DESCRIPTION
**Pull request by Ellega**
- fix #532 with Power FS and download All Minisite with Windows OS
- Hide .ajxp_meta file for others user who directly access to files in Repo with Windows Explorer

### CODE REVIEW

**Comment by cdujeu** [comment]
mmm, sorry i can't merge that. 
I get the point, but it's really too "local filesystem" specific. Is it so important to set this "Hidden" flag ? 
-c

**Comment by Ellega** [comment]
the same users manages their files from pydio or from Windows with file manager. 
this depends where the user is. In this case they can see and delete all file .ajxp_meta.
And if PowerFS is use for download All in minisite, .ajxp_meta is always in archive.
After our partners call us to ask what is this file ".ajxp_meta"
All of this is not enought clean and a bit risked in a pro use for me :-)

don't worry If it is your wish, close this issue.
I keep this ugly code only for myself :-)

**Comment by Ellega** [comment]
just a thought
I can understand very easily that my code is not the best :-))))
But this is not the first time that one deals specifically with Windows OS. No ?

**Comment by cdujeu** [comment]
mmm, struggling to find a clean way to do that... The problem is that you can still be on WIN OS, but currently plugged into another driver.
Questions: do we necessarily have to handle the different cases "already exists or not" for both the open mode and the application of hidden? Or on the other way, could we actually "read" the hidden status of the file directly inside the driver?

**Comment by Ellega** [comment]
Not sure to understand where is the risk with driver.
This is applied only if "driver = fsAccessWrapper" + WinOS = true). It is not enough ?

It is not necessary to handle the different cases "already exists or not".

After if this is merged or something similar, it is very easy for me to hide any file ".ajxp_meta" already existing and not hidden in the whole repo, with a simple manual command (attrib +h .ajxp_meta /S).

**Comment by erixtekila** [comment]
@cdjeu, Why not adding this feature ?
Isn't it the same as the '.' filename prefix for Unixes FS, which is very "filesystem specific" also  ?

Average windows users will delete them.
+1 for this feature.

**Comment by Ellega** [comment]
New PR posted 
https://github.com/pydio/pydio-core/pull/1077

**Pull request closed without merging**
