### PR TITLE
fixing encoding issues on powerFS pydio 6.5.2

### PR DESCRIPTION
**Pull request by Nanomani**

### CODE REVIEW

**Comment by cdujeu** [comment]
This one is 100% working ?

**Comment by Nanomani** [comment]
Arf. F..k No ! With workspace in pydio the answer is yes but minisite the answers is no. Nothing start with "download" or "download All". When I have some time I must check that. Sorry

**Comment by Nanomani** [comment]
Not sure the pb with minisite is exactely the same. 
Tested on an shared folder witout accent in "path" and without accent on files under this folder.
However is PowerFS is disable "download" and "download All" works well

**Comment by Nanomani** [comment]
my code must be more clean

**Pull request closed without merging**
