### PR TITLE
Fix path parsing - access.fs: Handle paths ending with a single # / access.smb: Handle paths containing and ending with a #

### PR DESCRIPTION
**Pull request by NHellFire**

### CODE REVIEW

**Comment by NHellFire** [comment]
Added 2 more commits. $path was being overwritten before the check for a single trailing #

**Comment by cdujeu** [comment]
Mmmm, you want to modify the heart of the reactor here... :-)
Do you have a usecase where you have a # in the path at this point??

**Comment by NHellFire** [comment]
Well, access.fs already handled paths containing a #, but access.smb
didn't. Quite a few people prefix folders with symbols to keep them sorted
to the top. Added trailing # for completeness (even if it's rarely going to
happen).

**Comment by cdujeu** [comment]
Did you try to test that on a "paginated" environment (folder listing broken into many pages) ?

**Comment by c12simple** [comment]
Fix on 6.5.1 but access.ftp has this bug.

**Pull request closed without merging**
