### PR TITLE
Develop fix1020

### PR DESCRIPTION
**Pull request by rbrdevs**
Posible solution to issue #1020 .
MessageHash contains default language strings.
It should be accessed via this._pydio in order to get new selected language strings.

### CODE REVIEW

**Comment by cdujeu** [comment]
i doubt it's doing any good, did you test it successfully? Global window.MessageHash & pydio.MessageHashare pointing to the same object. I think there's a server problem in the answer after saving the preferences.
-c

**Comment by rbrdevs** [comment]
Yes, I debug javascript code with Chrome Dev Tools and could see how strings in MessageHash on class.PydioIU.js contains default language ones, not new selected language ones.
I applied this fix and now language switching works fine.

**Comment by cdujeu** [comment]
ok i'll digg that, thanks for the hint.

**Comment by cdujeu** [comment]
I fixed it manually as we had to update the global MessageHash as well.

**Pull request closed without merging**
