### PR TITLE
Some LDAP authentication improvements

### PR DESCRIPTION
**Pull request by TesseractG**
- Support for TLS; you can now select ldap, ldaps or ldap+tls for the protocol.
- Support for jpegPhoto (avatar from LDAP); this required some front-end changes, too. Avatars are loaded from LDAP and embedded as a data:image/jpeg stream.
- Better support for fake memberOf, allowing usage of posixGroups; this is the main change.

You can now use posixUser and posixGroup objects from LDAP with the fake memberOf set to memberUid, the fake memberOf user attribute set to uid and the cn/dn selection set to Other. It was previously impossible to use an LDAP setup with posixGroups out of the box, because the fake memberOf always wanted a dn or part of a dn attribute; it never linked on uid.

### CODE REVIEW

**Comment by cdujeu** [comment]
Hello Gerard, 
Thanks for submitting! Ldap plugin is always very touchy, so please bear with us taking some time to review and test properly before merging. Meanwhile, can you kindly sign the CLA? See pydio.com > community > contribute instructions.
Thx
Charles

**Comment by TesseractG** [comment]
Hi Charles,

You are very welcome! I have signed and submitted the CLA as well, thanks for pointing that out, as I missed it before. Curious to see/hear if my LDAP changes are useful to anyone else!

Regards,
Gerard

**Comment by TesseractG** [comment]
I am curious if this is ever going to be merged? I am still using my branch and it works with FreeNAS, but would like to use a recent version of Pydio and keep up-to-date...

**Comment by c12simple** [comment]
Hello @TesseractG,
Could you please help me some example value of memberUid

**Comment by TesseractG** [comment]
Hi @c12simple,

The setup I use with LDAP now uses PosixGroup and PosixUser. Here is an example of a group entry (with some data redacted):

```
dn: cn=exec,ou=Groups,dc=org,dc=tld
cn: exec
gidNumber: 10003
memberUid: user1
memberUid: user2
memberUid: user3
objectClass: posixGroup
```

And here are some users:

```
dn: cn=user1,ou=Users,dc=org,dc=tld
cn: user1
description: CEO
displayName: User One
gidNumber: 10000
givenName: User
sn: One
initials: UO
mail: ceo@org.tld
loginShell: /bin/false
objectClass: posixAccount
objectClass: inetOrgPerson
uid: user1
uidNumber: 10002
userPassword: ****

dn: cn=user2,ou=Users,dc=org,dc=tld
cn: user2
description: CTO
displayName: User Two
gidNumber: 10000
givenName: User
sn: Two
initials: UT
mail: cto@org.tld
loginShell: /bin/false
objectClass: posixAccount
objectClass: inetOrgPerson
uid: user2
uidNumber: 10003
userPassword: ****

dn: cn=user3,ou=Users,dc=org,dc=tld
cn: user3
description: CFO
displayName: User Three
gidNumber: 10000
givenName: User
sn: Three
initials: UT
mail: cfo@org.tld
loginShell: /bin/false
objectClass: posixAccount
objectClass: inetOrgPerson
uid: user3
uidNumber: 10004
userPassword: ****
```

This is the standard LDAP layout for posixGroup and posixAccount, which can be used for authenticating users as system users on posix systems.

The matching is made between the "uid" attribute in the posixAccount and the memberUid in posixGroup.

**Comment by c12simple** [comment]
Hello,
Thank you for your info.
There is one thing: It'd better if we keep LDAP_VALUE_MEMBERATTR_IN_GROUP type (in core/src/plugins/auth.ldap/manifest.xml)
Because if we change the type of this param from "boolean" to "choice" (dn|cn|other) will break other's system after upgrade.

**Comment by cdujeu** [comment]
breaks upgrade. reopen if needed.

**Pull request closed without merging**
