### PR TITLE
Joomla-Bridge role mapping fix

### PR DESCRIPTION
**Pull request by rowbean**
Allows you to use the role mapping in pydio.
all credit goes to Dave who created that solution. His explanation should be added to the Joomla-Bridge how-to - https://pydio.com/forum/f/topic/joomla-roles-map-solution/

### CODE REVIEW

**Comment by cdujeu** [comment]
Hi @rowbean thanks, 
Sorry to bug you, could you kindly sign the CLA so that I can merge the PR? 
See https://pydio.com/community/contribute/contributor-license-agreement-cla
Cheers

**Comment by rowbean** [comment]
Hi @cdujeu, Im sorry but unfortunately i can't do that cause this code was made by Dave and as far as I understood this would be a violation against the CLA. Maybe you can take his fix and change it by yourself to prevent any problems?

**Comment by cdujeu** [comment]
yep no problem, i'll do that.

**Comment by cdujeu** [comment]
ok added manually added, @rowbean can you just verifiy it's working ok?

**Comment by rowbean** [comment]
Thanks. It did work with my version, but I'm going to test it with yours too and get back to you till saturday.

**Comment by rowbean** [comment]
Didn't have the time to check it on work last friday. I'll try to test it on monday.

**Comment by rowbean** [comment]
@cdujeu  Sorry for the late response. It works! There is only one issue. If you create a user in Joomla and you log in for the first time, the user is created and logged on in pydio, but the roles aren't set. If you then delete the user from pydio and log in again on joomla, the user is recreated and the roles are properly mapped.

**Pull request closed without merging**
