### PR TITLE
Imporved german translations of sharing function and fixed minor layout problems

### PR DESCRIPTION
**Pull request by huzergackl**

### CODE REVIEW

**Comment by cdujeu** [comment]
Hello @huzergackl sorry for coming back to you so late. The branch changed a lot since june, could you kindly resynchronize your translation files to the current develop status?
Thx

**Comment by cdujeu** [comment]
hi @huzergackl any plan to update this one?

**Comment by huzergackl** [comment]
hello @cdujeu, no problem. I merged the fork with current state of development

**Comment by cdujeu** [comment]
Coo, thx @huzergackl, merged. Do you work on this branch on a day-to-day basis? Spotted any problems? They were a lot of changes under the hood :-)

**Comment by huzergackl** [comment]
hi @cdujeu,
i am working on a virtual machine with the current state of development.
After correctly setting up grunt there were no javascript errors after all.
Also the main functionality seems to work without problems (but i only testet with FS driver).

Great work! :-)

A few things i have tested so far:
* Creating a repository
* Creating/uploading, renaming, deleting (recycle bin) and moving content per drag & drop
* Sharing feature
* Editing a text file
* Sorting and the different views
* My profile page
* Upgrade - pydio was upgraded step by step starting with 5.3 a year ago i think

**Comment by cdujeu** [comment]
Cool. Did you notice the performances improvements? They should be quite big.

**Comment by cdujeu** [comment]
And I still have to edit the Readme for the grunt :-)

**Pull request merged**
