### PR TITLE
Translation PT-BR

### PR DESCRIPTION
**Pull request by FredPassos**
Partial translation to Portuguese (Brazil)

### CODE REVIEW

**Comment by FredPassos** [comment]
@cdujeu It's my first time using git and github. If everything is OK, can you merge?
CLA already signed.

Thanks.

**Comment by cdujeu** [comment]
Hello fred, 
Thanks for your contribution! I'll definitely have a look soon. Unfortunately, we're already in "code-freeze" for next version (to be out very soon), so not sure I can merge right now. I keep you posted.
Charles

**Comment by FeoSilva** [comment]
Obrigado Fred!

**Comment by cdujeu** [comment]
He @FredPassos, wait a couple of days before going further in translation, we'll merge the brand new branch into develop, and there will be a Loooooot of changes! Stay tuned.

**Comment by cdujeu** [comment]
Hi @FredPassos 
We have now merged huge changes into the develop branch. Make sure to check the main README as you'll have to run `composer` in many places (like you have to run npm/grunt) to be able to develop.
Thank you so much in advance for updating your PR.

**Comment by cdujeu** [comment]
Hi fred, any plan to update this PR?

**Comment by FredPassos** [comment]
Hi Charles,

We just launched our Pydio (https://pastavirtual.mpmg.mp.br/) to about
5.000 users.
In this first weeks I am dedicated in this task. Only after I'll be able to
update the PR.

--
Frederico F. Passos
fred.passos@gmail.com

2016-09-21 4:56 GMT-03:00 Charles du Jeu <notifications@github.com>:

**Comment by cdujeu** [comment]
Hi @FredPassos if you can spend some time on translation, it's now or never! (it will have to wait after the the 7.0 release unfortunately...) :-)

**Comment by FredPassos** [comment]
@cdujeu Thanks for the merge.

I made a new [commit](https://github.com/FredPassos/pydio-core/commit/17c980299f5d1a6f9b01e3dfd60813bc79143da4), just after the merge. I need to make a new PR ou can you merge it?

**Pull request merged**
