### PR TITLE
Disable admin functions

### PR DESCRIPTION
**Pull request by andypmuc**
Allows you to disable admin functions workspaces as well as application parameters and developer ressources

### CODE REVIEW

**Comment by cdujeu** [comment]
Andy
Thanks for your PR. It's almost there... but not yet ;-)
Configurations parameters should certainly not be php constants defined in bootstrap_context.php ... 
Instead, you would define plugins parameters inside the access.ajxp_conf/manifest.xml ! 
Can you do that or do you need more info?
-c

**Comment by andypmuc** [comment]
To be honest not exactly. I could create a separated conf.php file and include it or with this?
        <param name="REMOTE_SORTING" type="boolean" label="CONF_MESSAGE[Remote Sorting]" description="CONF_MESSAGE[Force remote sorting when in paginated mode. Warning, this can impact the performances.]" default="true"/>
        <global_param name="PROBE_REAL_SIZE" type="boolean" label="CONF_MESSAGE[Real Size Probing]" description="CONF_MESSAGE[Use system command line to get the filesize instead of php built-in function (fixes the 2Go limitation)]" default="false"/>

**Comment by cdujeu** [comment]
mmm, I don't really like that... The problem being that it's not really clean. Why would you want to hide one section and not another? And how to edit all that if the main admin can't? Do you know that "group admins" have these sections disabled already?
-c

**Comment by andypmuc** [comment]
Didn't know this, because the changed code is older than that feature. For me it was an security feature. I made the initial installation and the main admin could not change the configuration as there is no reason to change it later. The hiding of the workspaces is a similar reason, because the I don't want someone accessing the main server directory. Using Windows I used users and access rights to avoid this, but if you use more than one installation of pydio in one domain. The admin can, which was avoided by altering the entries in mysql automatically with a trigger by applying a root path. I check the group admin feature.

**Comment by andypmuc** [comment]
I see why you don't like it now. Can the group admin create workspaces? In my installation he cannot.

**Comment by cdujeu** [comment]
Yes, but only if from templates: the super admin must create templates, and group admin can use them.
These workspaces will be accessible only to the current group users.
Can we close that one then?
-c

**Comment by andypmuc** [comment]
Yes, I did this in V3 oder something. Good, that I read the docu. With group admins it is obsolete and especially with AJXP_ALLOW_SUB_PATH and AJXP_GROUP_PATH.

**Pull request closed without merging**
