### PR TITLE
missing "," character in various en.php files

### PR DESCRIPTION
**Pull request by svetlemodry**
For translators to allow correct transfer of the .php text files to the .po format,
so that a CAT tool like OmegaT can be used to ease the translation, text lines
need to end with ",". Currently, some of the php files were missing this
character on the last text line of the file. This commit fixes this.

list of files was generated with this command
`for i in `find . -type f -name en.php`; do pcregrep -M '\"\n\)' "$i" && echo $i; done`

files for other languages than EN were not touched by me, but can be listed with this:
`for i in `find . -type f -name *.php`; do pcregrep -M '\"\n\)' "$i" && echo && echo $i; done | grep /i18n/`

### CODE REVIEW

**Comment by cdujeu** [comment]
Hi, 
My question would be: do you actually use such tools ? How do you then "translate back" from PO to php? I'm eager to find easier ways to get people contributing on the i18n..
-c

**Comment by svetlemodry** [comment]
Hi!
Yes, I've build a whole work flow for myself around this idea actually.
In the last version of OmegaT, there was a feature added to upload and share dictionaries created during the translation process via git. So in the final stage, it would be possible for a whole team of people to collaborate on a translation using this CAT tool connected to a repository.
Here in this repository is my source data for the [Czech Pydio translation](https://github.com/svetlemodry/pydio-to-czech).

The workflow looks like:
* clone pydio's original source code
* traverse the directories looking for en.php files and delete everything else
* transform files (en.php) that were left to .po files
 * format needs to be exact or strings will be missing in the exported files, hence this PR
 * translate-toolkit has a CLI command to move files between [php and po](http://docs.translatehouse.org/projects/translate-toolkit/en/stable-1.12.0/commands/php2po.html) formats
* load up omegat, do the translation
* export the translated files and transform them back to .php
* commit to upstream

With each translated string, OmegaT builds a personal dictionary that can be used for various projects. So the flow might seem as a bit overkill at the beginning, but it's strenght will be used later on with a bigger dictionary. And I wanted to find another way of translating various open source software by using standard command line tools, for which pydio is very good test case, as there are many files spread across the directory structure and not only 1-2 short files with the text strings.

Then on the other side a lot of projects seems to be using services like [Transifex](https://www.transifex.com/) or [Crowdin](https://crowdin.com/) which require no coding skills on the translators side.
Yet still if I participate on multiple projects on transifex, I have to write down a translation for things like "Save", "Open", etc. in each of them. With OmegaT, these words are translated once, added into a shared dictionary and will be prefilled for any project added and opened in the app.

Cheers
J

**Comment by svetlemodry** [comment]
Any decision on (not) having this PR included? Else, I'd start to work on translating the relevant files to Czech again.

**Comment by cdujeu** [comment]
hi, sorry, i did not take time to merge. Just need to test that everything is fine after merge, will do asap.

**Pull request merged**
