### PR TITLE
fixing german translation

### PR DESCRIPTION
**Pull request by mawit**
Small fix for the german translation of the encfs plugin

### CODE REVIEW

**Comment by huzergackl** [comment]
Hi Charles, i did a quick review. This pr can be merged as it is.

**Comment by cdujeu** [comment]
hi @mawit can you quickly sign the CLA so that I can merge? See https://pydio.com/fr/community/contribute/contributor-license-agreement-cla

**Comment by mawit** [comment]
Hi @cdujeu I signed the CLA about a one and a halve year ago for a previous PR (https://github.com/pydio/pydio-core/pull/1104).

**Comment by cdujeu** [comment]
arg sorry, i was looking at the bottom of the list i guess....

**Pull request merged**
