### PR TITLE
Updated Korean translation

### PR DESCRIPTION
**Pull request by joona0825**
Not fully translated yet, but I just request pull now.
After updating more translation, I'll request pull again.

### CODE REVIEW

**Comment by cdujeu** [comment]
Hello @joona0825 can you make sure to first sign the CLA (See Contribute tab on the website)?
Then tell me when you are ready to merge.
Thx

**Comment by cdujeu** [comment]
hello @joona0825 any news on that PR?

**Comment by joona0825** [comment]
Sorry I was too busy these days.... If I have time, I'll read CLA and update this pull request. Sorry

**Comment by cdujeu** [comment]
no worries, just checking :-)

**Comment by cdujeu** [comment]
no feedback. Reopen if possible.

**Pull request closed without merging**
