### PR TITLE
Update de.php

### PR DESCRIPTION
**Pull request by kluckow**
Is that ok if those html entities are replaced by the umlauts?

### CODE REVIEW

**Comment by cdujeu** [comment]
Hi @kluckow I think you did not sign the CLA (see https://pyd.io/contribute/cla)! can you do that before we merge?
-thx

**Comment by cdujeu** [comment]
oups sorry, already signed, forget my previous comment

**Comment by kluckow** [comment]
Hey,
I am not sure if I said it correctly, so here another try...

I made updates in the core.ajaxplorer/i18n/de.php file.
Namely I did the following regarding the umlauts:
image

The reason why I did it was that you actually could see those html entities instead of the umlauts when using Pydio and getting those messages containing umlauts.
Nobody wants to see... 
image
...on a button or on anything else.

And now I see in the mentioned de.php file, that its back to the state before I made some changes, atleast most of the changes.
Does that mean my suggestion for updating the translation was not possible or not working for any reason?
Or am I doing anything wrong with the encoding?

Thank you in advance!

**Comment by cdujeu** [comment]
Hi, 
No you are definitely right, we should use ä in UTF-8 rather than html entities (pydio will recode to htmlentities only when necessary).
I merged a huuuge PR with a massive german update, and probably here there were these errors again? 
Could you grab very last code and fix that again? Sorry about the extra work.
Charles

**Comment by kluckow** [comment]
No problem,

atleast now I got the idea of what is right and what is wrong.

So, no worries! :)

kluckow

**Pull request merged**
