### PR TITLE
Utils: Do not sanitize password fields

### LINKED ISSUE #695: Samba passwords sanitized
Samba passwords are being sanitized. My password contains a < and I'm unable to view that, I have to manually edit the database and correct the password.

### PR DESCRIPTION
**Pull request by NHellFire**
Fixes #695

### CODE REVIEW

**Comment by cdujeu** [comment]
Hello @NHellFire 
Thanks for contributing, did you sign the CLA already? See https://pyd.io/contribute/cla
Thx
-c

**Comment by NHellFire** [comment]
Done

**Comment by cdujeu** [comment]
Should be ok, but still we have to check that this cannot be used as a security whole (which is the main point of sanitization).

**Comment by c12simple** [comment]
fixed: https://github.com/pydio/pydio-core/commit/4a64194c0b24c9dcb99a5528c31c26d09255b67c

**Pull request closed without merging**
