### PR TITLE
Spanish and catalan translations

### PR DESCRIPTION
**Pull request by Salva-G**
Spanish and catalan translations

### CODE REVIEW

**Comment by cdujeu** [comment]
Hi @Salva-G sorry there are some conflicts, can you update your branch and update the PR ?

**Comment by Salva-G** [comment]
Updated! Thanks!

**Comment by cdujeu** [comment]
Merged but... please BEWARE when you submit a PR, that at least your PHP code is valid. You were (again) missing a comma in the core.ajaxplorer > ca.php file , and that can break the whole app if you switch to catalan.

**Comment by cdujeu** [comment]
FYI You can see directly next to the PR the Travis check.

**Pull request merged**
