### PR TITLE
Some fix for ZOHO Editor 

### PR DESCRIPTION
**Pull request by Ellega**
- Fix charset bug

sharing works well with pydio 6.3.1 with zoho editor enable.
(tested with xlsx, docx )

but only in case where there is no accent in file name or in parent folders (path)
It seems that zoho editor don’t like special characters…

- Add option for change lang

### CODE REVIEW

**Comment by cdujeu** [comment]
So we can close #1039  ?

**Comment by Ellega** [comment]
Yep

**Comment by cdujeu** [comment]
@Ellega sorry I made some changes that breaks that PR, can you update it?
Thx

**Comment by Ellega** [comment]
I create a new PR

**Pull request closed without merging**
