### PR TITLE
Complete Spanish translation

### PR DESCRIPTION
**Pull request by ChuckDaniels87**
Complete translation of Pydio to Spanish including all the plugins.

~This is a work in progress~. I've first copied all missing es.php files from en.php version. I'm translating all those files one by one but it will take me some time to complete this.

I've created the PR to track the process of translation and to look for errors that could be introduced.

### CODE REVIEW

**Comment by ChuckDaniels87** [comment]
I've completed the translation of all possible localization strings to Spanish. I've also fixed some previous translations.

I've tried to achieve a consistent translation across all plugins. As much as I could, I kept approximately the same length of the translated strings to avoid visual problems on the GUI. 

If there is any kind of typo please notify me, I'll gladly fix any translation issue. Also, I'll try to keep Spanish translation up to date.

**Comment by ChuckDaniels87** [comment]
If there is any interest in this PR, I will fix the new conflicts of the localization files.

**Comment by ChuckDaniels87** [comment]
I've rebased the branch and fixed the conflicts.

**Comment by ChuckDaniels87** [comment]
I've rebased the branch to current develop and fixed conflicts.

It would be good to receive some feedback from developers.

I know this PR changes many files but they are all localisation files. There are many commits to easen conflict resolution and code revision but I can squash them if it is needed.

**Comment by cdujeu** [comment]
Hi, thanks, I'll have a look - How do you like the new UI ? ;-)

**Comment by ChuckDaniels87** [comment]
Thanks @cdujeu ! 

The new UI is really nice. I'm glad to see that you keep working on Pydio and polishing every aspect of it. It is a really matured and reliable option for file sharing and cloud storaging. 

Everybody here in my team is very happy with Pydio. Congrats and keep working hard!

**Comment by cdujeu** [comment]
@ChuckDaniels87 you don't seem to have signed the CLA, I cannot merge the PR currently, can you check https://pydio.com/en/community/contribute ? 
Thx

**Comment by ChuckDaniels87** [comment]
@cdujeu I thought that I've signed CLA long ago. I've signed it again. 👍

**Comment by ChuckDaniels87** [comment]
I've made some clean up since I've translated some plugins that are not longer included in Pydio.

**Comment by ChuckDaniels87** [comment]
@cdujeu I've noticed that new UI is still missing many internationalization strings and entire files. I'll try to keep updating and fixing this PR until the new UI is finished. 

Just out of curiosity, any estimated time for the new UI release?

**Comment by cdujeu** [comment]
Hey Ismael, the sooner the better!!! We are currently in codefreeze, the official release date is 16th of may, and I would love to merge your PR next tuesday if possible.
thaaaank you so much in advance

**Comment by cdujeu** [comment]
Big up @ChuckDaniels87  :-)

**Pull request merged**
