### PR TITLE
Integrate Mozilla PDF.JS PDF viewer plugin

### PR DESCRIPTION
**Pull request by ghost**
...

### CODE REVIEW

**Comment by cdujeu** [comment]
Hey @garnetius, this look promising! Thank you for contributing and welcome on board :-)
Will try to review that and merge asap. 
Quick question did you already sign the CLA (see pyd.io/contribute/cla)?

**Comment by garnetius** [comment]
Hello Charles, glad you're liking it!

I will sign the CLA right now. Also, I created this forum thread as a general public announcement: https://pyd.io/f/topic/pdf-js-viewer-integration/

**Comment by garnetius** [comment]
Forgot to mention that integrated PDF.JS is based on pdfjs-1.0.907-dist.zip release from [official website](http://mozilla.github.io/pdf.js/).

I have added comments everywhere I made adjustments in PDF.JS viewer.css and viewer.js (just search for “Pydio”).

**Comment by erixtekila** [comment]
Hi, is there an online pdf viewer + annotation library somewhere that could also be added ?

**Comment by garnetius** [comment]
@Ellega, thanks for the heads up. It didn’t pop up in my testing probably because the box I was testing on actually didn’t have ImageMagick installed. I’ve applied your fix and the pull request has been automatically updated now. Thanks again.

**Comment by cdujeu** [comment]
Hi @garnetius 

I had a quick test run, I did not check the code yet. Seems to be working good, panel resize is working (ok), tested filenames with utf8 or url characters (ok). Still, I detected some issues, see below.

*Blocking*
 * Cannot open two PDF at the same time
 * Shared file: preview is not working, there's a trick with the minisite_session parameter to add (see other editors like video)

*Major*
 * We loose the thumbnail preview capability: we would have to mix something with imagick for that...
 * How do we handle non-supporting browsers (IE8) with a fallback to imagick

*Minor*
 * i18n issue: the editor label is wrong for me in french (i18n cache cleared already)


I actually ended up merging the PR, except that I re-enabled pdf extension inside imagemagick for the moment. So maybe you can make sure to restart a new PR from the develop branch that now contains your plugin. I can have a look at the "Shared file" case, I let your the "open multiple" issue, right ? 

Charles

**Pull request merged**
