### PR TITLE
Adding Italian translations for some plugins

### PR DESCRIPTION
**Pull request by DepaMarco**
Adding Italian translations for plugins:
* 'authfront.cyphered'
* 'authfront.duosecurity'
* 'authfront.http_basic'
* 'authfront.http_server'
* 'authfront.keystore'
* 'authfront.otp'
* 'authfront.session_login'

and updating 'core.ajaxplorer' one.

### CODE REVIEW

**Comment by 7omate** [comment]
Hi, would you be interested in helping translate https://github.com/pydio/pydio-sync ? I started it, but I'd like an Italian native to check it before publishing it. If you're interested reply here or drop me a mail thomas _at_*` pydio.com

**Comment by DepaMarco** [comment]
@7omate Hi! Yeah, sure! I will help you... Do you have already write something to review?

**Comment by DepaMarco** [comment]
@7omate Ok, I started answer you on the specific commit on sync repo ;)

**Comment by DepaMarco** [comment]
@cdujeu Hi.
You can merge, for me :) I'm not planning to go ahead for the moment...

**Pull request merged**
