### PR TITLE
Fix group overlay for other LDAP directories

### PR DESCRIPTION
**Pull request by agaikwad**
Adding support for the group membership attribute used in other
directories.
Active Directory uses: MemberOf
Sun directory server uses: isMemberOf
IBM TDS uses: ibm-AllGroups.

We have this change in production and have to make the change every time we upgrade. We were hoping to submit the change back to you guys.

### CODE REVIEW

**Comment by c12simple** [comment]
Hello agaikwad 
Thank you for your update.
Do you have any virtual-appliance of Sun directory and IBM TDS ?
I would like to test on such system before commiting
Again, Than you

**Comment by agaikwad** [comment]
Hello, we used to have Sun DS but we don't anymore. Hence I did not put it in the pull request as I had no way to test it. We have IBM TDS in production and I have this change made to Pydio and ibm-allgroups assigned as a roleid and it is working correctly. Unfortunately we don't have any test installs of the directory server. This is a link to the IBM documentation on the attribute:
http://www-01.ibm.com/support/knowledgecenter/SSVJJU_6.4.0/com.ibm.IBMDS.doc_6.4/ds_ag_dir_mgmt_group_attrib_types.html

**Comment by cdujeu** [comment]
we should find a way to make this more generic, otherwise we'll endup with key == "a" || key =="b" || key == "c"...

**Comment by agaikwad** [comment]
@cdujeu - Were you looking for inputs from me to make this more generic?
I agree this should be more generic because this line is pretty bad hard coding. The only way to change this is touching the code. Perhaps a better options may be to default to memberof but give users an options to overwrite that field in the settings page?
```
if ($key == "memberof")
```
Not sure what the best solution is but we just made the same change while upgrading from 6.0.8 to 6.2. We would prefer not touching the source between upgrades.

**Comment by cdujeu** [comment]
@c12simple is this integrated in the new plugin?

**Comment by c12simple** [comment]
Yes, new group membership attribute is define as a variable so it covers all above cases.

**Pull request closed without merging**
