### PR TITLE
Pluploader faster GUI loading

### PR DESCRIPTION
**Pull request by GeraldST**
I investigated loading times for the widget as @alozzy suggested in #781 and came up with small improvements by optimizing loading of js-libraries - at least for first time loading. Cause in most cases they should come from the client cache anyhow which should be really fast. See explanation in Commit.

### CODE REVIEW

**Comment by cdujeu** [comment]
Alan (@alozzy) working for you?

**Comment by GeraldST** [comment]
Included fix for minisite problem

**Comment by alozzy** [comment]
I've had no issues with the optimizations that GeraldST made for the PLUpload loadtimes. I haven't done any testing with the new changes he's implemented for the minisite problem.

**Comment by lolllpop** [comment]
https://github.com/pydio/pydio-core/pull/781 + https://github.com/pydio/pydio-core/pull/785 fix plupload for me, its loading time and now its integration into minisites. Many thanks, @GeraldST

**Pull request merged**
