### PR TITLE
Fix Sort By when using pagination

### PR DESCRIPTION
**Pull request by olivierapex6**
Hi we just wrote that code to fix the Sort By , when using the pagination. 
The error code that we have was ".foreach is not a function" and then blank page. This code is using a FOR loop and drain the object inside the object properly.
Please push that code

### CODE REVIEW

**Comment by cdujeu** [comment]
Hi, i'll push a proper patch for that part (not exactly the same as yours). However, are you able to actually revert the sorting (asc/desc) when selecting the same current sorting? i think this is broken too

**Comment by olivierapex6** [comment]
Hi Charles

Yes, I confirm, asc/desc is working fine now.

**Comment by cdujeu** [comment]
just pushed some code, can you test mine?

**Comment by cdujeu** [comment]
it's cleaner, as we don't want to access the "_object" of the old side prototypeJS hash maps, but use pure javascript Map() instead

**Comment by olivierapex6** [comment]
Hi Charles. 

Yes it is also working fine with your commit.

Thanks for your help.

**Pull request closed without merging**
