### PR TITLE
Extend buffer read to account for MSOOXML files

### PR DESCRIPTION
**Pull request by rcmarotz**
The original buffer read of 100 bytes is not enough to determine whether a application/zip file is actually a Microsoft Open Office XML file.  By reading more of the file, finfo can make a determination of the file type.  One of the issues is that the header size that required is dependent on the first archive file size.  I think 2KB will be enough to determine MSOOXML files, 3KB may be safer.

### CODE REVIEW

**Comment by ghecquet** [comment]
hi @rcmarotz we tried to reproduce that but expanding the buffer was not enough to make it work.
Do you have some specific settings for your file_info php extension (like magic file or...) ? 
-c

**Comment by rcmarotz** [comment]
I had been playing with a magic file.  But once I extended the size to 2KB, I stopped using my magic file.  I search around for any code remnants left over dealing with magic but couldn't find anything.  What file type are you trying to find the info on?

**Comment by cdujeu** [comment]
Hi @rcmarotz 
There were major changes in the develop branch, could you kindly check and submit a brand new clean PR? 
Make sure to read the README about the composer step required to use development mode.
thx
-c

**Comment by cdujeu** [comment]
already in code

**Pull request closed without merging**
