### PR TITLE
fixing encoding issues on PowerFS 6.5.x

### PR DESCRIPTION
**Pull request by Nanomani**

### CODE REVIEW

**Comment by Nanomani** [comment]
works 100 % with repo (download or compress).

Ps : 
In Minisite "Download/Download all" have no effect (no error, no message). Just nothing append
Tested on minisite where the "full path" and all files haven't accent to be sure.

Another bug not introduce by this PR.
add this PR can be only better in all case :-)

**Comment by Nanomani** [comment]
another one with your last code who works at 100 % posted

**Comment by cdujeu** [comment]
is the last code making it work on windows? 
beware, if you are updating from github, make sure to re-grunt core.tasks

**Comment by Nanomani** [comment]
Yep
see here my last PR tested with lastest core.tasks code :-)

**Pull request closed without merging**
