### PR TITLE
All message in table ajxp_log truncated, if accent in path or file name (win OS)

### PR DESCRIPTION
**Pull request by Nanomani**
All message in table ajxp_log truncated (column "params"), if accent in path or file name (win OS)
=> this mean the same issue in pydio =>settings => display Logs

### CODE REVIEW

**Comment by cdujeu** [comment]
Hey @Nanomani, we have merged namespaces => develop. You can start working again :-)
Please check the main README, you will have to run composer (in the same way you have to run npm install/grunt) to be able to develop.

**Comment by cdujeu** [comment]
Note: Regarding encoding, it has been simplified A LOT, and encoding/decoding is now only happening at a low-level, just before writing/reading to/from the storage. Otherwise, everywhere in the app we use utf8. Should be much more easy to debug.

**Comment by cdujeu** [comment]
closing for now, to be checked with new version

**Comment by Nanomani** [comment]
all seems ok with 6.5.1
thx

**Pull request closed without merging**
