### PR TITLE
Set metastore files hidden if possible

### PR DESCRIPTION
**Pull request by Nanomani**

### CODE REVIEW

**Comment by cdujeu** [comment]
it means we have to reset the hidden flag each time we write into the file (even if it existed before)?

**Comment by Nanomani** [comment]
@cdujeu 

I made 2 changes : 

1 - Line 333 

`TextEncoder::toStorageEncoding` have a bad result and it is useless. 
I have tested my PR with accent in path. :-) 

2 - line 322 to 326

I had to change this otherwise the metafile is not hidden the first time in case where the metafile doesn't exist yet.

I hope to have been understandable.

**Comment by Nanomani** [comment]
Nope. with your code metafile is flagged hidden each time but not the first time when the metafile doesn't exist. It is all. Perhaps I don't understand the question ... sorry :-) 

`if($scope === AJXP_METADATA_SCOPE_GLOBAL && $this->nodeIsLocalWindowsFS($ajxpNode) && file_exists($metaFile)){
                  
$nodeIsWinLocal = true;`

**Comment by cdujeu** [comment]
So maybe you can just add one last line : inside the "if(file_exists...)" test, set $nodeIsWinLocal = false so that we don't set the hidden flag each time we write in the existing file. Ok ?

**Comment by Nanomani** [comment]
Ok

**Comment by Nanomani** [comment]
PR Updated

**Pull request merged**
