### PR TITLE
Plupload testing

### PR DESCRIPTION
**Pull request by sed-sytarchuk**
This extends the plupload functionality checking if a file is locked before uploading.

Uses the native simple_lock plugin.

### CODE REVIEW

**Comment by cdujeu** [comment]
Hi @sed-sytarchuk 
Sorry for the soooo late answer. FYI we already implement the apply_check_hook action that you can call with the actionName="before_change" parameter (see fsActions.xml and its implementation in the AbstractAccessDriver). Could you use that one instead of adding another action inside the PLUploader plugin?
Thx
Charles

**Comment by sed-sytarchuk** [comment]
Sure.

Do you want me to change my pull request to reflect these changes or 
remove it altogether?

**Comment by cdujeu** [comment]
As you like, maybe simpler to submit a brand new PR using the existing access point (apply_check_hook) ? 
-c

**Comment by sed-sytarchuk** [comment]
Will do.

**Pull request closed without merging**
